USE [master]
GO

/****** Object:  Database [DemoAppRepository]    Script Date: 10/19/2019 12:56:41 AM ******/
CREATE DATABASE [DemoAppRepository]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DemoAppRepository', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.BIGBOSSSQL\MSSQL\DATA\DemoAppRepository.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DemoAppRepository_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.BIGBOSSSQL\MSSQL\DATA\DemoAppRepository_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoAppRepository].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DemoAppRepository] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DemoAppRepository] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DemoAppRepository] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DemoAppRepository] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DemoAppRepository] SET ARITHABORT OFF 
GO

ALTER DATABASE [DemoAppRepository] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DemoAppRepository] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DemoAppRepository] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DemoAppRepository] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DemoAppRepository] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DemoAppRepository] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DemoAppRepository] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DemoAppRepository] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DemoAppRepository] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DemoAppRepository] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DemoAppRepository] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DemoAppRepository] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DemoAppRepository] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DemoAppRepository] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DemoAppRepository] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DemoAppRepository] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DemoAppRepository] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DemoAppRepository] SET RECOVERY FULL 
GO

ALTER DATABASE [DemoAppRepository] SET  MULTI_USER 
GO

ALTER DATABASE [DemoAppRepository] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DemoAppRepository] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DemoAppRepository] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DemoAppRepository] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DemoAppRepository] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DemoAppRepository] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DemoAppRepository] SET  READ_WRITE 
GO

